# General Jekyll Config
highlighter: rouge
url: http://celebes.github.io
lsi: false
exclude: [LICENSE, CNAME, README.md, .gitignore]
timezone: Europe/Warsaw

# Theme customization - please change from the defaults!
theme_settings:
  # Color for top bar, links, etc
  highlight_color: '#06afa2'

  # Profile links on the left sidebar, leave blank to ignore
  social:
    #github: Celebes
    #bitbucket: philipj
    #hacker_news: swanson
    #stackexchange: 348619
    #stackoverflow: 1644096
    #twitter: _swanson
    facebook: kgurniak
    #tumblr: animalygifs
    #linkedin: philipjagielski
    #gplus: 110552447039675960964

  # "Hi, I'm _______"
  name: Krzysztof Gurniak
  email: kris1337@gmail.com
  tagline: "weak opinions, strongly held"

  # Google Analytics key, leave blank to ignore
  google_analytics_key: UA-xxxx-x

  # Toggle "Postings are my own" disclaimer in footer
  show_disclaimer: false
